module.exports = {
  projects: [
    '<rootDir>/apps/ng-app',
    '<rootDir>/libs/shared/assets',
    '<rootDir>/libs/shared/styles',
    '<rootDir>/libs/shared/environments',
    '<rootDir>/libs/shared/data-access',
    '<rootDir>/apps/react-app',
    '<rootDir>/libs/utils/types',
    '<rootDir>/libs/shared/ui-components-angular',
    '<rootDir>/libs/shared/ui-components-react',
    '<rootDir>/libs/shared/types',
    '<rootDir>/libs/shared/mappers',
    '<rootDir>/libs/utils/dates',
    '<rootDir>/libs/utils/observables',
    '<rootDir>/libs/utils/arrays',
    '<rootDir>/libs/utils/objects',
    '<rootDir>/libs/utils/strings',
  ],
}
